/**
 * Generated by orval v8.0.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import useSwr from 'swr'
import type { Key, SWRConfiguration } from 'swr'

export interface BaseResponse {
  message?: string
}

/**
 * @summary Root
 */
export type rootGetResponse200 = {
  data: BaseResponse
  status: 200
}

export type rootGetResponseSuccess = rootGetResponse200 & {
  headers: Headers
}
export type rootGetResponse = rootGetResponseSuccess

export const getRootGetUrl = () => {
  return `/`
}

export const rootGet = async (
  options?: RequestInit
): Promise<rootGetResponse> => {
  const res = await fetch(getRootGetUrl(), {
    ...options,
    method: 'GET',
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: rootGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as rootGetResponse
}

export const getRootGetKey = () => [`/`] as const

export type RootGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof rootGet>>
>

/**
 * @summary Root
 */
export const useRootGet = <TError = Promise<unknown>>(options?: {
  swr?: SWRConfiguration<Awaited<ReturnType<typeof rootGet>>, TError> & {
    swrKey?: Key
    enabled?: boolean
  }
  fetch?: RequestInit
}) => {
  const { swr: swrOptions, fetch: fetchOptions } = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey =
    swrOptions?.swrKey ?? (() => (isEnabled ? getRootGetKey() : null))
  const swrFn = () => rootGet(fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions
  )

  return {
    swrKey,
    ...query,
  }
}
